export enum CategoryFinanseEnum {
  CAT1 = 'BANCA - odstąpienie/rozwiązanie/zwrot',
  CAT2 = 'Inwestycje/Wyniki finansowe/Roliczenie kosztów',
  CAT3 = 'Księgowanie/Przeksięgowanie składek/ Stan płatności',
  CAT4 = 'List indywidualny/Promesa',
  CAT5 = 'ML - Indeksacja',
  CAT6 = 'ML - inny wniosek',
  CAT7 = 'ML - Wznowienia',
  CAT8 = 'ML - zapytania',
  CAT9 = 'Obniżenie wysokości składki',
  CAT10 = 'Oferta specjalna',
  CAT11 = 'Polecenie zapłaty - pytanie ogólne',
  CAT12 = 'Premia na PUL/ULM 3,4',
  CAT13 = 'Propozycja rocznicowa - Pytanie ogólne',
  CAT14 = 'Propozycja rocznicowa - rezygnacja z propozycji',
  CAT15 = 'Transfer OFE',
  CAT16 = 'Ubezpieczenie bezskładkowe',
  CAT17 = 'Umowa dodatkowa - rezygnacja',
  CAT18 = 'Wpłata składki dodatkowej/lokacyjnej/IKE/IKZE',
  CAT19 = 'Wysokość GSU',
  CAT20 = 'Wznowienie umowy',
  CAT21 = 'Zawieszenie opłacania składek/Skrócenie zawieszenia',
  CAT22 = 'Zestawienie składek OFE (STMT)',
  CAT23 = 'Zestawienie składek TUNŻ/IKE/IKZE',
  CAT24 = 'Zmiana częstotliwości',
}
