// Build information, automatically generated by `ng-info`
const build = {
    version: "0.0.7",
    timestamp: "Wed Mar 25 2026 07:44:02 GMT+0100 (Central European Standard Time)",
    message: null,
    git: {
        user: "Asier de Diego",
        branch: "master",
        hash: "f41803",
        fullHash: "f4180358dff81de9239a9cfb67c879fc6776bf08"
    }
};

export default build;