// Build information, automatically generated by `ng-info`
const build = {
    version: "1.0.0",
    timestamp: "Fri Mar 27 2026 07:36:02 GMT+0100 (Central European Standard Time)",
    message: null,
    git: {
        user: "Asier de Diego",
        branch: "master",
        hash: "e2367b",
        fullHash: "e2367b638ad09f73b449c5b100a9f5921a59f28d"
    }
};

export default build;