// Build information, automatically generated by `ng-info`
const build = {
    version: "0.0.6",
    timestamp: "Mon Mar 23 2026 14:39:42 GMT+0100 (Central European Standard Time)",
    message: null,
    git: {
        user: "Asier de Diego",
        branch: "master",
        hash: "983dba",
        fullHash: "983dbaa31bfc48c86d9f93662a1465ec5bb39816"
    }
};

export default build;